### ISSUE TITLE
Cannot map same path to multiple drives

### ISSUE THREAD

**Issue by stephen-hill** [winfsp/sshfs-win#222]
Hi

- sshfs-win v3.5.20160
- winfsp v1.7
- Windows 10 Version 1909 (OS Build 18363.997)

This is more of a query as to why this is not possible, but if it can be fixed by sshfs-win, then I suggest it should be.

I have discovered that it is not possible to connect to the same location using multiple drive letters.

Example:
```
> net use W: \\sshfs.kr\username@host\usr\local\www
The command completed successfully.

> net use X: \\sshfs.kr\username@host\usr\local\www
System error 67 has occurred.

The network name cannot be found.
```

The only thing that changed between these two commands was the drive letter. W to X.

Cheers
Stephen

**Comment by billziss-gh** [comment]
The problem here is that you are trying to spawn **two** file systems with the same UNC prefix: `\\sshfs.kr\username@host\usr\local\www`. This is explicitly disallowed by Windows design.

It appears that what you want to do is have two drives point into the same file system. In this case I suggest that you look into `subst` or similar utility to create the second drive.
